### ISSUE TITLE
GitHub Wiki

### ISSUE THREAD

**Issue by ElectronicsArchiver** [SGG-Modding/ModUtil#3]
You might wanna consider **[Not Using GitHub Wiki]**.

<br>

*( I saw that you have a separate repo for generating the docs,*
*though that I'm referring to not use it to display the content )*

*As the guide shows, an alterentive would be having a separate*
*repo, which you already do, so why not have the generated files*
*be there instead?*

[Not USing GitHub Wiki]: https://github.com/MarkedDown/Wiki

**Comment by MagicGonads** [comment]
We have plans to create our own documentation platform for SGG-Modding, that isn't to be viewed from GitHub so it can be indexed by search engines.

For now I have kept the documentation and code (of ModUtil) separate because I don't update the documentation to match the code at the moment anyway (it's already fragmented without there being more than one version or contributor)

Thanks for the suggestion though, keep doing what you're doing.

**Comment by ElectronicsArchiver** [comment]
> We have plans to create our own documentation platform for SGG-Modding, that isn't to be viewed from GitHub so it can be indexed by search engines.

Well you could utilize a separate repository 
and enable GitHub Pages, that will allow you
to have it be indexed.
